{'application': True,
 'author': 'Oudu Software',
 'category': 'Extra Tools',
 'data': ['views/res_config_settings_views.xml', 'views/assets.xml'],
 'depends': ['oudu_base', 'web'],
 'images': ['static/description/banner.png'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'Oudu Desktop',
 'sequence': -980,
 'summary': 'Native desktop capabilities for Odoo with the Oudu Desktop client',
 'support': 'info@oudu.net',
 'version': '14.0.1.2',
 'website': 'https://desktop.oudu.top'}
